title: The Last Wave
description: The Last Wave project
source: docs
<<<<<<< Updated upstream
remote_theme: pages-themes/architect@v0.2.0
=======
remote_theme: pages-themes/cayman@v0.2.0
>>>>>>> Stashed changes
plugins:
- jekyll-remote-theme
